name: nfl_venv
channels:
  - defaults
dependencies:
  - python=3.7.5
  - pip=19.3.1
  - pip:
    - numpy==1.26.2
    - pandas==2.1.4
    - scipy==1.11.4
    - scikit-learn==1.3.2
    - matplotlib==3.8.2
    - seaborn==0.13.0
    - jupyter==1.0.0
    - jupyter-console==6.6.3
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.1
    - jupyter_client==8.6.0
    - jupyter_core==5.5.0
    - jupyter_server==2.12.1
    - jupyter_server_terminals==0.5.0
    - jupyterlab==4.0.9
    - jupyterlab-widgets==3.0.9
    - jupyterlab_pygments==0.3.0
    - jupyterlab_server==2.25.2
